### ISSUE TITLE
Cannot import name MBTilesBuilder

### ISSUE THREAD

**Issue by bohwaz** [makinacorpus/landez#41]
I'm trying the first example of the readme on Debian wheezy:

```
 $ sudo easy_install landez
Searching for landez
Reading http://pypi.python.org/simple/landez/
Best match: landez 2.3.0
Downloading https://pypi.python.org/packages/source/l/landez/landez-2.3.0.zip#md5=b0ae5f3fbdcc81b7a7bc42283da6db2a
Processing landez-2.3.0.zip
Running landez-2.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SNDc2Y/landez-2.3.0/egg-dist-tmp-ixZLkU
Adding landez 2.3.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/landez-2.3.0-py2.7.egg
Processing dependencies for landez
Searching for mbutil
Reading http://pypi.python.org/simple/mbutil/
Best match: mbutil 0.2.0
Downloading https://pypi.python.org/packages/source/m/mbutil/mbutil-0.2.0.tar.gz#md5=959fee1068a40eafda7159e66c547808
Processing mbutil-0.2.0.tar.gz
Running mbutil-0.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a3A01Q/mbutil-0.2.0/egg-dist-tmp-BfKAX4
zip_safe flag not set; analyzing archive contents...
Adding mbutil 0.2.0 to easy-install.pth file
Installing mb-util script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/mbutil-0.2.0-py2.7.egg
Finished processing dependencies for landez

 $ python landez.py
Traceback (most recent call last):
  File "landez.py", line 2, in <module>
    from landez import MBTilesBuilder
  File "/tmp/landez.py", line 2, in <module>
    from landez import MBTilesBuilder
ImportError: cannot import name MBTilesBuilder
```

I checked and the module is correctly set up in  /usr/local/lib/python2.7/dist-packages/ so I don't get it.

**Comment by leplatrem** [comment]
Can you try to rename your script to something different than ``landez.py`` ?

**Comment by bohwaz** [comment]
What the hell? It works. Thanks. But why? ^^

**Comment by leplatrem** [comment]
It's python behaviour about absolute imports (I think)
Maybe @jpcw would have a more precise answer :)

**Comment by bohwaz** [comment]
Oh yes now it makes sense. Thanks.
